/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */ 

fn main() {

    let term_limit = 4000000;

    let mut term;

    let mut p = 1;
    let mut c = 2;

    let mut sum_of_evens = 2;

    loop {
        term = p + c;

        if term > term_limit { break; }

        if (term % 2) == 0 {
            sum_of_evens += term;
            //println!("term: {} <--- even | sum: {}", term, sum_of_evens);
        } else {
            //println!("term: {}", term);
        }

        p = c;
        c = term;
    }

    println!("sum of even: {}", sum_of_evens);

}
